### ISSUE TITLE
Poročilo

### ISSUE THREAD

**Issue by jaanos** [sarakovacic/APPR-2017-18#2]
Prosim poskrbi za svoje poročilo (`projekt.Rmd`), da boš lahko v četrtek predstavila svoj projekt. V njem torej posodobi opis podatkov (lahko vzameš iz `README.md`) ter nariši nekaj zanimivih grafov oziroma zemljevidov. Del, ki je ostal iz vzorca, pobriši, da se ti bo poročilo prevedlo. Svetujem, da iz glave odstraniš vrstico `runtime: shiny` - po shranjevanju se bo pojavil gumb *Knit*, s katerim lahko poročilo prevedeš v obliko HTML. Pazi tudi, da kličeš ustrezne programe - namesto `uvoz/uvoz.r` bo torej treba poklicati `uvoz/uvozpodatkov.R` (velikost črk je pomembna, saj nekateri sistemi ločijo male od velikih črk).

**Comment by sarakovacic** [comment]
Pozdravljeni!
Vsebinsko sem dokončala poročilo, vendar se mi zdi, da ga ne prevede (ne pokaže grafov, tudi po kliku na "knit".  Kaj je narobe? 
Zanima me tudi, kam naj napišem  "warning = FALSE", da ne bo prikazovalo opozoril.
Hvala, 
Sara

**Comment by sarakovacic** [comment]
Sedaj mi je uspelo prevesti poročilo, vendar še vedno kaže nekaj obevstil. 

![33332rrrrrrr](https://user-images.githubusercontent.com/30369207/35066037-77c327a2-fbcf-11e7-83ee-daef49d2c5c0.PNG)

![dddddddddddddddd](https://user-images.githubusercontent.com/30369207/35066306-6f14b9b2-fbd0-11e7-91cb-9e4bc5b2bc52.PNG)

Kako naj jih odpravim?
Hvala

**Comment by sarakovacic** [comment]
Mi je uspelo, hvala vseeno.

**Comment by jaanos** [comment]
V redu, zdaj ti poročilo prevede, tako da bom dodal povezavo do trenutnega commita na repoztorij za zagovore. Če boš še kaj spreminjala in boš želela posodobiti povezavo, odpri issue na [repozitoriju za zagovore](https://github.com/jaanos/APPR-zagovori) (glej navodila spodaj).

Še to: če dobiš na osi grafa zelo veliko številskih oznak, je to znak, da podatki niso bili pravilno uvoženi in bo potrebno poskrbeti za ustrezne pretvorbe v števila. Poleg tega razpredelnica `gozd_slo2` ni v obliki *tidy data*, saj so tri od štirih stolpcev z meritvami na isti skali in jih bo torej treba spraviti v en stolpec, površina pa naj bo posebej:
```R
gozd_slo <- read_csv2("podatki/gozdvslo.csv", locale = locale(encoding = "Windows-1250"),
                      skip = 2, n_max = 4) %>%
  melt(id.vars = 1, variable.name = "leto", value.name = "kolicina") %>%
  mutate(leto = parse_number(leto))
colnames(gozd_slo)[1] <- "meritev"
povrsina_gozda_slo <- gozd_slo %>% filter(meritev == "Površina gozda (ha)") %>%
  select(leto, povrsina = kolicina)
gozd_slo <- gozd_slo %>% filter(meritev != "Površina gozda (ha)")
```
Potem lahko graf `g3` rišeš iz razpredelnice `povrsina_gozda_slo`, graf `g33` pa iz ustrezno filtrirane razpredelnice `gozd_slo`:
```R
g33 <- ggplot(gozd_slo %>% filter(meritev == "Letni prirastek (1000 m3)")) +
  aes(x = leto, y = kolicina, group = 1) +
  geom_line(color = 'pink', position = "jitter", size = 1.2) +
  xlab("Leto") + ylab("Prirastek") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  ggtitle("Letni prirastek površine gozda - Slovenija")
```
