### ISSUE TITLE
Zemljevid

### ISSUE THREAD

**Issue by sarakovacic** [sarakovacic/APPR-2017-18#3]
Pozdravljeni!
Imam težave pri risanju zemljevida. Nekaj mi je uspelo napisati, vendar mi ni točno jasno zakaj ne dela in kaj je narobe.
Hvala za odgovor,
Lp, Sara

**Comment by jaanos** [comment]
Sklepam, da želiš prikazati povprečno površino čez leta (za tista leta, za katera imaš podatke). Potem si razpredelnico `povprecje` pripravi tako:
```R
povprecje <- regije.tidy %>% group_by(regija) %>% summarise(povrsina = mean(povrsina, na.rm = TRUE))
```
Stolpca `leto` torej ne podajaj v `group_by`, saj bi tako dobila nazaj iste podatke (tj., vsaka skupina bi vsebovala samo eno vrstico).

**Comment by sarakovacic** [comment]
Hvala za ta popravek, sedaj se graf nariše pravilno. 
Ugotovila sem tudi, da ni narisalo regij s šumniki, saj pri uvozu ni bil definiran encoding = "UTF8".
