### ISSUE TITLE
Poročilo

### ISSUE THREAD

**Issue by sarakovacic** [sarakovacic/APPR-2017-18#4]
Pozdravljeni!
Imam nekaj težav pri pisanju poročila. 
Osnovna težava je ta, da se mi nekateri grafi zdijo preveliki in bi jih rada zmanjšala in pomaknila skupaj v eno vrstico (enega ob drugega).   Zmanjšanje grafov ni problem, ne vem pa kako jih pomakniti skupaj v vrstico. Našla sem funkcijo multiplot() ( zapisana v vizualizacija.r), vendar se tudi ta ne obnaša točno kot bi hotela (je pa boljše). Pravtako ta multiplot v poročilu napiše zraven še NULL, in ne vem točno kaj je narobe. (slika spodaj)
![rmarkdown](https://user-images.githubusercontent.com/30369207/37292792-00d83ba6-2612-11e8-9460-45a166c2a256.PNG)

Hvala za odgovor,
Lep pozdrav,
Sara Kovačič

**Comment by jaanos** [comment]
Z `multiplot` ne uporabljaj `print`, saj ta funkcija grafe le izriše, vrne pa `NULL` (ki je privzeto skrit). Če želiš grafa izrisati v vrstici, uporabi parameter `cols = 2` (torej da izrisuješ v dveh stolpcih). Seveda bi bilo potrebno naslove potem skrajšati ali izpisati v dveh vrsticah, da bodo v celoti vidni.

Namesto `multiplot` lahko uporabiš tudi funkcijo `ggarrange` iz knjižnice `ggpubr`. Če se pa odločiš ohraniti `multiplot`, pa napiši, kje si jo dobila (npr. v komentar ob funkciji).
