### ISSUE TITLE
Zaključevaje projekta

### ISSUE THREAD

**Issue by sarakovacic** [sarakovacic/APPR-2017-18#5]
Pozdravljeni!
Zanima me, ali je še kaj takega, kar bi bilo potrebno popraviti pred oddajo projekta?
Lp,
Sara Kovačič

**Comment by jaanos** [comment]
Svetoval bi le en lepotni popravek: pri opisu razpredelnici postavi imena stolpcev (in tudi spremenljivk) med \`\` namesto med `''`, da se bodo izpisali kot koda. Sklepam, da si se odločila, da aplikacije Shiny ne vključiš v poročilo?

Drugih pripomb nimam, tako da bom dodal povezavo na repozitorij za zagovore, z @alenFMF pa se lahko domeniš za termin zagovora. Če boš še kaj spreminjala, mi prosim javi, da posodobim povezavo.

**Comment by sarakovacic** [comment]
Pozdravljeni!
Shiny aplikacije nisem vključila v poročilo ker vsebuje iste grafe, ki so že tako ali tako vključeni v poročilo. Me pa vseeno zanima kakšen je ukaz, če bi to želela storiti? 
Drugače sem popravila slovnične in lepotne napake, tako da lahko posodobite povezavo. 
Sara

**Comment by sarakovacic** [comment]
Sem našla odgovor na svoje vprašanje pri projektu od @ajdastare.

```{r shiny, echo = FALSE, message=FALSE, warning=FALSE}
shinyAppDir("shiny", options=list(width="100%", height=600))
```

**Comment by jaanos** [comment]
V redu, sem posodobil.

**Comment by sarakovacic** [comment]
Pozdravljeni!
Prosim, če še enkrat posodobite projekt. 
Lp,
Sara Kovačič

**Comment by jaanos** [comment]
Posodobljeno.
